version: '{build}'

branches:
  only:
  - master

clone_folder: c:\projects\chillout

image:
- Visual Studio 2017

configuration:
  - Debug
#- Release

platform:
- x64

# environment:
#   matrix:
#   - arch: Win64
#   # - arch: #does not work, Release|x64 not a valid target

matrix:
  fast_finish: true

before_build:
  - mkdir build
  - cd build
  - cmake --version
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake .. -G "NMake Makefiles"

build_script:
  - nmake.exe
