version: '{build}'

clone_folder: c:\projects\chillout

image:
- Visual Studio 2017

configuration:
  - Debug
#- Release

platform:
- x64

before_build:
 - mkdir build
 - cd build
 - cmake --version
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - cmake .. -G "NMake Makefiles"

build_script:
  - nmake.exe

test_script:
  - nmake test
