version: 0.0.{build}-{branch}

clone_folder: c:\projects\chillout

image:
- Visual Studio 2017

configuration:
  - Debug
#- Release

platform:
- x64

before_build:
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake --version
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - cmake .. -G "NMake Makefiles"

build_script:
  - nmake.exe

test_script:
  - nmake test
  - set "crash_dump=c:\projects\chillout\src\tests\chillout_test.dmp"
  - if not exist "%crash_dump%" EXIT /B 1
  - powershell Push-AppveyorArtifact "%crash_dump%" -FileName chillout_test.dmp
